### ISSUE TITLE
vehicle_global_position and vehicle_local_position don't display any data

### ISSUE THREAD

**Issue by derickcoder44** [PX4/px4_ros_com#223]
Hello, 
I have a Holybro Pixhawk 6x Pro running px4 v1.15. I'm connecting to this via ethernet to raspberry pi 5 running ROS2 Rolling. I tried to add the topics in `PX4-Autopilot/src/modules/uxrce_dds_client/dds_topics.yaml`:
```
publications:
  - topic: /fmu/out/vehicle_global_position
    type: px4_msgs::msg::VehicleGlobalPosition
    rate_limit: 50.
  - topic: /fmu/out/vehicle_local_position
    type: px4_msgs::msg::VehicleLocalPosition
    rate_limit: 50.
```
I compiled and flashed my pixhawk with this build. 

I tried also to match my px4 version with px4_ros_com (PX4-Autopilot v1.15.4, and px4_ros_com v1.15) and rebuilt px4_ros_com. 

When I do `ros2 topic list` I see both of the topics. But when I do `ros2 topic echo /fmu/out/vehicle_global_position`  and `ros2 topic echo /fmu/out/vehicle_local_position` don't see anything (same thing with `ros2 topic hz [topic_name]`). 

I've checked in the mavlink console and `ekf2 status`, `orb -t vehicle_local_position`, and `orb -t vehicle_global_position` all showed good values  – I was testing outside. I've verified that the other topics are working. 

Would anyone know why I'm not `getting vehicle_global_position` and `vehicle_local_position` data in ROS2? Did I skip one of the steps of adding a new uORB topic into ROS?
